# Generated by Django 4.2.2 on 2024-04-14 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-date"]},
        ),
    ]
