# Generated by Django 4.2.2 on 2024-04-14 06:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_alter_comment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="usersWatching",
            field=models.ManyToManyField(
                related_name="watchedListings", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
